namespace FFmpegRuntimeForUWP
{
    [default_interface]
    runtimeclass FFmpegMain
    {
		FFmpegMain();

		static void getConfiguration();
		static winrt::hstring getVersionInfo();
		static FFmpegMain getFMInstance();
    }

}
