namespace FFmpegRuntimeForUWP
{

    [default_interface]
    runtimeclass FFmpegMain
    {
		FFmpegMain();

		static void getConfiguration();

		
		static void getVersionInfo();
		static FFmpegMain getFMInstance();


    }

}
